export const FETCH_LESSONINFO= 'FETCH_LESSONINFO';
export const FETCH_LESSONINFO_REQ= 'FETCH_LESSONINFO_REQ';
export const FETCH_LESSONINFO_SUC= 'FETCH_LESSONINFO_SUC';
export const FETCH_LESSONINFO_FAI= 'FETCH_LESSONINFO_FAI';
export const FETCH_USERINFO = 'FETCH_GITHUB_USERINFO';
export const FETCH_USERINFO_REQ = 'FETCH_GITHUB_USERINFO_REQ';
export const FETCH_USERINFO_SUC = 'FETCH_GITHUB_USERINFO_SUC';
export const FETCH_USERINFO_FAI = 'FETCH_GITHUB_USERINFO_FAI';
export const FETCH_SMSG = 'FETCH_SMSG';
export const FETCH_SMSG_REQ = 'FETCH_GITHUB_SMSG_REQ';
export const FETCH_SMSG_SUC = 'FETCH_GITHUB_SMSG_SUC';
export const FETCH_SMSG_FAI = 'FETCH_GITHUB_SMSG_FAI';
export const FETCH_CDS = 'FETCH_CDS';
export const FETCH_CDS_REQ = 'FETCH_GITHUB_CDS_REQ';
export const FETCH_CDS_SUC = 'FETCH_GITHUB_CDS_SUC';
export const FETCH_CDS_FAI = 'FETCH_GITHUB_CDS_FAI';

export const FETCH_SERACH = 'FETCH_SERACH'

export const FETCH_STA = 'FETCH_STA';
export const FETCH_STA_REQ = 'FETCH_GITHUB_STA_REQ';
export const FETCH_STA_SUC = 'FETCH_GITHUB_STA_SUC';
export const FETCH_STA_FAI = 'FETCH_GITHUB_STA_FAI';